# Aliases for reuse
aliases:
  - &working_directory ~/combine-utils

  - &restore_yarn_cache
    keys:
      - v1-yarn-cache-{{ checksum "yarn.lock" }}

  - &save_yarn_cache
    key: v1-yarn-cache-{{ checksum "yarn.lock" }}
    paths:
      - node_modules

  - &install
    name: Installing
    command: yarn --frozen-lockfile

  - &npm_auth_token
    name: Configure Circle to add the authToken to ~/.npmrc
    command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc

# Defaults for node environment
node18Environment: &node18Environment
  docker:
    - image: circleci/node:18
  working_directory: *working_directory

version: 2
jobs:
  install:
    <<: *node18Environment
    steps:
      - checkout
      - restore-cache: *restore_yarn_cache
      - run: *npm_auth_token
      - run: *install
      - save-cache: *save_yarn_cache
  lint:
    <<: *node18Environment
    steps:
      - checkout
      - restore-cache: *restore_yarn_cache
      - run:
          name: "Linting"
          command: "yarn lint"
  test:
    <<: *node18Environment
    steps:
      - checkout
      - restore-cache: *restore_yarn_cache
      - run:
          name: "Testing"
          command: "yarn test"
  typescript:
    <<: *node18Environment
    steps:
      - checkout
      - restore-cache: *restore_yarn_cache
      - run:
          name: "Type checking"
          command: "yarn ts"
  build:
    <<: *node18Environment
    steps:
      - checkout
      - restore-cache: *restore_yarn_cache
      - run:
          name: Building
          command: yarn build
      - persist_to_workspace:
          root: *working_directory
          paths:
            - dist/*
  publish:
    <<: *node18Environment
    steps:
      - checkout
      - restore-cache: *restore_yarn_cache
      - attach_workspace:
          at: *working_directory
      - run:
          name: Publishing
          command: yarn release

workflows:
  version: 2
  build:
    jobs:
      - install
      - lint:
          requires:
            - install
      - test:
          requires:
            - install
      - typescript:
          requires:
            - install
      - build:
          requires:
            - lint
            - test
            - typescript
      - publish:
          requires:
            - build
          filters:
            branches:
              only: master
